#!/usr/bin/perl -w
open(F1, "$ARGV[0]");
open(F2, "$ARGV[1]");

@lines1 = <F1>;
@lines2 = <F2>;

while(@lines1 && @lines2) {
	print shift @lines1;
	print shift @lines2;
}

while(@lines1 && !@lines2) {
	print shift @lines1;
}

while(@lines2 && !lines1) {
	print shift @lines2;
}
